'@context':
  '@vocab': https://w3id.org/valueflows#
  xsd: http://www.w3.org/2001/XMLSchema#
  qudt: http://qudt.org/schema/qudt/
  unit: http://qudt.org/vocab/unit/
  time: http://www.w3.org/2006/time#
  time:inXSDDateTimeStamp:
    '@type': xsd:dateTimeStamp
  alice: https://alce.example/
  bob: https://bob.example/
  claudia: https://claudia.example/
  notary: https://notary.example/
  miner: https://miner.example/
  jesus: https://jesus.example/
  joe: https://joe.example/

'@graph':

  - '@id': bob:8e5fe80d-a769-4bd5-89e5-2136d33eab9f
    '@type': Process
    skos:note: fruit distribution in January

  - '@id': notary:9bd19194-a36d-4a1f-896b-8082887962cb
    '@type': ExchangeAgreement

  - '@id': claudia:33e8933b-ff73-4a01-964a-ca7a98893083
    '@type': Process
    skos:note: transporting Bob's package

  - '@id': bob:60f4204e-b8d2-4026-8577-102c3f82c0af
    '@type': EconomicResource
    skos:note: Bob's package
    currentQuantity:
      qudt:unit: unit:Unitless
      qudt:numericValue: 1

  - '@id': claudia:ad56a7ed-be3c-4937-a3fb-0f156bcd2c47
    '@type': Commitment
    action: load
    inputOf: claudia:33e8933b-ff73-4a01-964a-ca7a98893083
    involves: bob:60f4204e-b8d2-4026-8577-102c3f82c0af
    committedQuantity:
      qudt:unit: unit:Unitless
      qudt:numericValue: 1
    under: notary:9bd19194-a36d-4a1f-896b-8082887962cb
    provider: claudia
    receiver: bob

  - '@id': claudia:6078f30a-b15b-4b1c-8e77-797abae11378
    '@type': Commitment
    action: unload
    outputOf: claudia:33e8933b-ff73-4a01-964a-ca7a98893083
    involves: bob:60f4204e-b8d2-4026-8577-102c3f82c0af
    committedQuantity:
      qudt:unit: unit:Unitless
      qudt:numericValue: 1
    under: notary:9bd19194-a36d-4a1f-896b-8082887962cb
    provider: claudia
    receiver: bob

  - '@id': bob:e56fd654-7b94-4d96-8e60-de39e08329a7
    '@type': Commitment
    action: give
    resourceClassifiedAs: http://www.wikidata.org/entity/Q89 # apples
    committedQuantity:
      qudt:unit: unit:Kilogram
      qudt:numericValue: 10
    under: notary:9bd19194-a36d-4a1f-896b-8082887962cb
    provider: bob
    receiver: claudia

  - '@id': claudia:86ad6e22-7640-4b93-972a-db7177ab2616
    '@type': Commitment
    action: service
    serviceClassifiedAs: http://www.wikidata.org/entity/Q7590 # transport
    outputOf: claudia:33e8933b-ff73-4a01-964a-ca7a98893083
    inputOf: bob:8e5fe80d-a769-4bd5-89e5-2136d33eab9f
    under: notary:9bd19194-a36d-4a1f-896b-8082887962cb
    provider: claudia
    receiver: bob

# https://github.com/valueflows/valueflows/issues/270#issuecomment-383317953  
# Transfer a cryptocurrency that requires a fee

  - '@id': faircoin:d4d2fd71-34f2-41c3-b1c5-19ad5ed2da59
    '@type': EconomicResource
    classifiedAs: http://www.wikidata.org/entity/Q21002847 # Faircoin

  - '@id': faircoin:583e83d9-a46d-44ff-bd71-88513a1d83c0
    '@type': EconomicResource
    classifiedAs: http://www.wikidata.org/entity/Q21002847 # Faircoin

  - '@id': faircoin:e4783bef-9006-490c-9c03-389272c7444d
    '@type': EconomicResource
    classifiedAs: http://www.wikidata.org/entity/Q21002847 # Faircoin

  - '@id': miner:23799c14-c368-4653-a584-83bf9ae8b82a
    '@type': Process
    skos:note: transaction processing

  - '@id': notary:e18c808c-929a-450d-9d0d-3b3f531bc126
    '@type': ExchangeAgreement
    skos:note: exchange between Alice and Bob

  - '@id': notary:5d2fe7da-b91b-4dab-91d9-68db80c1feb7
    '@type': ExchangeAgreement
    skos:note: exchange between Alice and miner

  - '@id': miner:6405b8ad-0ac2-4d58-abdb-0808903c78ad
    '@type': EconomicEvent
    action: give
    affects: faircoin:d4d2fd71-34f2-41c3-b1c5-19ad5ed2da59
    inputOf: miner:23799c14-c368-4653-a584-83bf9ae8b82a
    under: notary:5d2fe7da-b91b-4dab-91d9-68db80c1feb7
    observedQuantity:
      qudt:unit: unit:Unitless
      qudt:numericValue: 200
    
  - '@id': miner:e02e3f6b-420a-4ba8-89b0-909d7363ce07
    '@type': EconomicEvent
    action: receive
    affects: faircoin:583e83d9-a46d-44ff-bd71-88513a1d83c0
    inputOf: miner:23799c14-c368-4653-a584-83bf9ae8b82a
    under:
      - notary:5d2fe7da-b91b-4dab-91d9-68db80c1feb7
      - notary:e18c808c-929a-450d-9d0d-3b3f531bc126
    observedQuantity:
      qudt:unit: unit:Unitless
      qudt:numericValue: 199
    provider: alice
    receiver: bob

  - '@id': miner:9f112621-3f13-4f48-a3e2-fd2ca99493cd
    '@type': EconomicEvent
    action: receive
    affects: faircoin:e4783bef-9006-490c-9c03-389272c7444d
    outputOf: miner:23799c14-c368-4653-a584-83bf9ae8b82a
    under: notary:5d2fe7da-b91b-4dab-91d9-68db80c1feb7
    observedQuantity:
      qudt:unit: unit:Unitless
      qudt:numericValue: 1
    provider: alice
    receiver: miner

  - '@id': miner:e72f7d1d-4f0a-4518-a44c-96658cafda95
    '@type': EconomicEvent
    action: service
    serviceClasifiedAs: http://www.wikidata.org/entity/Q844565 # Transaction processing
    outputOf: miner:23799c14-c368-4653-a584-83bf9ae8b82a
    under: notary:5d2fe7da-b91b-4dab-91d9-68db80c1feb7
    provider: miner
    receiver: alice


# https://github.com/valueflows/valueflows/wiki/Use-Cases-and-Requirements#pick-up-truck-distributing-farmers-product
# Pick-up truck distributing farmers product
# Small pick-up truck loads boxes of products from different farmers. Then it drives around and distributes them to consumers. Consumers haven't per-ordered food and the driver makes agreements with them on spot based on Proposals each of the farmers provided. Driver offers distribution to farmers as service under independent agreement with each farmer, ownership of products goes directly from producer to consumer.

  - '@id': jesus:f325a950-5737-488d-b122-8f21114d0eb0
    '@type': EconomicResource
    skos:note: Jesus' pick-up truck
    classifiedAs: http://www.wikidata.org/entity/Q215601 # pickup truck
    conformsTo: http://www.atlismotorvehicles.com/xt-truck
    currentQuantity:
      qudt:unit: unit:Unitless
      qudt:numericValue: 1

  - '@id': jesus:fdf65158-0223-4740-8ace-5323baa9fd07
    '@type': EconomicResource
    skos:note: turck battery
    classifiedAs: http://www.wikidata.org/entity/Q267298 # battery
    currentQuantity:
      qudt:unit: unit:Kilowatthour
      qudt:numericValue: 80

  - '@id': alice:3584c5eb-5b15-4c71-853e-0470fc34bbcb
    '@type': EconomicResource
    skos:note: Alice's apples
    clasifiedAs: http://www.wikidata.org/entity/Q89 # apple
    currentQuantity:
      qudt:unit: unit:Kilogram
      qudt:numericValue: 410

  - '@id': jesus:9396d2d1-ded3-4b1c-8144-1c024e641030
    '@type': EconomicResource
    skos:note: apples on the truck
    clasifiedAs: http://www.wikidata.org/entity/Q89 # apple
    currentQuantity:
      qudt:unit: unit:Kilogram
      qudt:numericValue: 0

  - '@id': bob:c404cff5-19c7-453d-b0d8-d8e96055bd0c
    '@type': EconomicResource
    skos:note: Bob's pears
    classifiedAs: http://www.wikidata.org/entity/Q13099586 # pear
    currentQuantity:
      qudt:unit: unit:Kilogram
      qudt:numericValue: 720

  - '@id': jesus:856c43b1-0a63-445f-a56f-707b257f086e
    '@type': EconomicResource
    skos:note: pears on the truck
    classifiedAs: http://www.wikidata.org/entity/Q13099586 # pear
    currentQuantity:
      qudt:unit: unit:Kilogram
      qudt:numericValue: 0

  - '@id': jesus:9cb4944b-d26d-4774-a530-d18f2747c0d8
    '@type': Process
    skos:note: Mon Jan 7th 2019 distribution

  - '@id': jesus:68cabaf3-deb8-4bd5-a439-798263abe35a
    '@type': EconomicEvent
    action: work
    inputOf: jesus:9cb4944b-d26d-4774-a530-d18f2747c0d8
    observedTime:
      time:intervalStarts:
        time:inXSDDateTimeStamp: 2019-01-07T10:00:00-5:00
      time:intervalEnds:
        time:inXSDDateTimeStamp: 2019-02-07T17:00:00-5:00

  - '@id': jesus:8baa8ff7-9c1e-4586-ae7b-79d620a3cac9
    '@type': EconomicEvent
    action: use
    affects: jesus:f325a950-5737-488d-b122-8f21114d0eb0 # pickup truck
    inputOf: jesus:9cb4944b-d26d-4774-a530-d18f2747c0d8
    observedQuantity:
      qudt:unit: unit:Unitless
      qudt:numericValue: 1
    observedTime:
      time:intervalStarts:
        time:inXSDDateTimeStamp: 2019-01-07T10:00:00-5:00
      time:intervalEnds:
        time:inXSDDateTimeStamp: 2019-02-07T17:00:00-5:00

  - '@id': jesus:f0b8bfb1-ed29-4ab0-aabd-f5e2a3515626
    '@type': EconomicEvent
    action: consume
    affects: jesus:fdf65158-0223-4740-8ace-5323baa9fd07 # pickup battery
    inputOf: jesus:9cb4944b-d26d-4774-a530-d18f2747c0d8
    observedQuantity:
      qudt:unit: unit:Kilowatthour
      qudt:numericValue: 42

  - '@id': jesus:daa2ec3b-2c1a-4eb1-839f-8dcec1a1f93a
    '@type': EconomicEvent
    skos:note: distribution service for alice
    action: service
    serviceClassifiedAs: http://www.wikidata.org/entity/Q867147 # distribution
    outputOf: jesus:9cb4944b-d26d-4774-a530-d18f2747c0d8
    under: notary:e5b209f6-d84b-4ef2-8d70-a17197029308
    provider: jesus
    receiver: alice

  - '@id': jesus:bd5806d6-4a36-45b9-b3b6-3e7d361a5a14
    '@type': EconomicEvent
    skos:note: distribution service for bob
    action: service
    serviceClassifiedAs: http://www.wikidata.org/entity/Q867147 # distribution
    outputOf: jesus:9cb4944b-d26d-4774-a530-d18f2747c0d8
    under: notary:991a873e-70cb-4e5d-8809-387d7c1af92f
    provider: jesus
    receiver: bob

  - '@id': jesus:a3277840-54b9-497e-9cf6-1902eda1584f
    '@type': Process
    skos:note: picking up apples from Alice

  - '@id': jesus:c27ba90d-b182-494c-84aa-719004a63f9e
    '@type': Process
    skos:note: pickupg up pears from Bob

  - '@id': jesus:a4ceeeff-0cfd-40e8-84e9-be64b3cf8cc6
    '@type': EconomicEvent
    action: split
    affects: alice:3584c5eb-5b15-4c71-853e-0470fc34bbcb # alice's apples
    inputOf: jesus:a3277840-54b9-497e-9cf6-1902eda1584f # picking up apples from Alice
    observedQuantity:
      qudt:unit: unit:Kilogram
      qudt:numericValue: 80
    provider: alice
    receiver: jesus

  - '@id': jesus:a31a3b48-0c7b-481c-a9f8-d3e579267d2a
    '@type': EconomicEvent
    action: merge
    affects: jesus:9396d2d1-ded3-4b1c-8144-1c024e641030 # apples on the truck
    outputOf: jesus:a3277840-54b9-497e-9cf6-1902eda1584f # picking up apples from Alice
    observedQuantity:
      qudt:unit: unit:Kilogram
      qudt:numericValue: 80
  
  - '@id': jesus:80e9ef99-5876-4529-8fcc-6f55060c3b3d
    '@type': EconomicEvent
    action: work
    inputOf: jesus:a3277840-54b9-497e-9cf6-1902eda1584f # picking up apples from Alice
    includedIn: jesus:68cabaf3-deb8-4bd5-a439-798263abe35a # all the work today
    provider: jesus
    receiver: alice
  
  - '@id': jesus:80e9ef99-5876-4529-8fcc-6f55060c3b3d
    '@type': EconomicEvent
    action: service
    outputOf: jesus:a3277840-54b9-497e-9cf6-1902eda1584f # picking up apples from Alice
    inputOf: jesus:9cb4944b-d26d-4774-a530-d18f2747c0d8 # Mon Jan 7th 2019 distribution

  - '@id': jesus:2d117224-9e34-4e86-adae-3a80ff5b8a49
    '@type': EconomicEvent
    action: split
    affects: bob:c404cff5-19c7-453d-b0d8-d8e96055bd0c # Bob's pears
    inputOf: jesus:c27ba90d-b182-494c-84aa-719004a63f9e # pickupg up pears from Bob
    observedQuantity:
      qudt:unit: unit:Kilogram
      qudt:numericValue: 45
    provider: bob
    receiver: jesus

  - '@id': jesus:a31a3b48-0c7b-481c-a9f8-d3e579267d2a
    '@type': EconomicEvent
    action: merge
    affects: jesus:856c43b1-0a63-445f-a56f-707b257f086e # pears on the turck
    outputOf: jesus:c27ba90d-b182-494c-84aa-719004a63f9e # pickupg up pears from Bob
    observedQuantity:
      qudt:unit: unit:Kilogram
      qudt:numericValue: 45

  - '@id': jesus:80e9ef99-5876-4529-8fcc-6f55060c3b3d
    '@type': EconomicEvent
    action: work
    inputOf: jesus:c27ba90d-b182-494c-84aa-719004a63f9e # pickupg up pears from Bob
    includedIn: jesus:68cabaf3-deb8-4bd5-a439-798263abe35a # all the work today
    provider: jesus
    receiver: bob
  
  - '@id': jesus:80e9ef99-5876-4529-8fcc-6f55060c3b3d
    '@type': EconomicEvent
    action: service
    outputOf: jesus:c27ba90d-b182-494c-84aa-719004a63f9e # pickupg up pears from Bob
    inputOf: jesus:9cb4944b-d26d-4774-a530-d18f2747c0d8 # Mon Jan 7th 2019 distribution

  - '@id': jesus:2c335f13-9896-4362-8d38-b9e409200297
    '@type': Process
    skos:note: processing transaction with Joe

  - '@id': notary:9087abc4-6f2b-4f1f-9c56-611b7f7302a3
    '@type': ExchangeAgreement
    skos:note: exchanging apples for Ollin
  
  - '@id': notary:9087abc4-6f2b-4f1f-9c56-611b7f7302a3
    '@type': ExchangeAgreement
    skos:note: exchanging pears for work

  - '@id': notary:2145d38e-848d-4165-9a1e-3e31beba9b66
    '@type': ExchangeAgreement
    skos:note: total transaction with Joe

  - '@id': jesus:80e9ef99-5876-4529-8fcc-6f55060c3b3d
    '@type': EconomicEvent
    action: service
    outputOf: jesus:2c335f13-9896-4362-8d38-b9e409200297 # transaction with Joe
    inputOf: jesus:9cb4944b-d26d-4774-a530-d18f2747c0d8 # Mon Jan 7th 2019 distribution

  - '@id': jesus:a1222849-2963-4c5e-ae63-d71d9d60bcc1
    '@type': EconomicEvent
    action: split
    affects: jesus:9396d2d1-ded3-4b1c-8144-1c024e641030 # apples on the truck
    inputOf: jesus:2c335f13-9896-4362-8d38-b9e409200297 # transaction with Joe
    under:
      - notary:9087abc4-6f2b-4f1f-9c56-611b7f7302a3 # exchanging apples for Ollin
      - notary:2145d38e-848d-4165-9a1e-3e31beba9b66 # total transaction with Joe
    observedQuantity:
      qudt:unit: unit:Kilogram
      qudt:numericValue: 5
    provider: alice
    receiver: joe

  - '@id': jesus:b8cf1198-c984-43d7-9316-657748d84895
    '@type': EconomicEvent
    action: split
    affects: jesus:856c43b1-0a63-445f-a56f-707b257f086e # pears on the turck
    inputOf: jesus:2c335f13-9896-4362-8d38-b9e409200297 # transaction with Joe
    under:
      - notary:9087abc4-6f2b-4f1f-9c56-611b7f7302a3 # exchanging pears for work
      - notary:2145d38e-848d-4165-9a1e-3e31beba9b66 # total transaction with Joe
    observedQuantity:
      qudt:unit: unit:Kilogram
      qudt:numericValue: 10
    provider: bob
    receiver: joe

  - '@id': joe:1bfbd442-44b8-4b14-9615-8ea4fc9c17c5
    '@type': Commitment
    action: split
    resourceClassifiedAs: http://circuloollines.org/ollin
    committedQuantity:
      qudt:unit: unit:Unitless
      qudt:numericValue: 100
    under: 
      - notary:9087abc4-6f2b-4f1f-9c56-611b7f7302a3 # exchanging apples for Ollin
      - notary:2145d38e-848d-4165-9a1e-3e31beba9b66 # total transaction with Joe
    provider: joe 
    receiver: alice

  - '@id': joe:6af016ca-d82b-482a-b36b-e2991b2efbe0
    '@type': Commitment
    action: work
    commitedTime:
      time:intervalStarts:
        time:inXSDDateTimeStamp: 2019-01-09T10:00:00-5:00
      time:intervalEnds:
        time:inXSDDateTimeStamp: 2019-02-09T12:00:00-5:00
    under:
      - notary:9087abc4-6f2b-4f1f-9c56-611b7f7302a3 # exchanging pears for work
      - notary:2145d38e-848d-4165-9a1e-3e31beba9b66 # total transaction with Joe
    provider: joe 
    receiver: bob
